name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: lein deps
    - name: Compile java
      run: lein javac
    - name: Run tests
      run: lein test
